# Site settings
title: Nossos vereadores
description: O que fazem, onde estão, como se reproduzem
keywords: Vereadores, Política, Controle social
author: Analytics
baseurl: "/vereadores-site/" # the subpath of your site, e.g. /blog/
url: "https://antonioricardojr.github.io" # the base hostname & protocol for your site
